# Generated by Django 4.1.5 on 2023-01-19 15:40

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='link_color',
            field=colorfield.fields.ColorField(blank=True, default='#523BB8', image_field=None, max_length=18, samples=None),
        ),
    ]
