# Generated by Django 4.1.5 on 2023-01-21 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_video_age_restricted'),
        ('backend', '0034_channel_link_color'),
    ]

    operations = [
    ]
